### ISSUE TITLE
Access on admin/action_logs error

### ISSUE THREAD

**Issue by Dryusdan** [glitch-soc/mastodon#639]
Hi
I found a problem on my instance, when I check uri `/admin/action_logs` I have a 500's error. The log print this : 
```
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] method=GET path=/admin/action_logs format=html controller=Admin::ActionLogsController action=index status=500 error='ActionView::Template::Error: No route matches {:account_username=>nil, :action=>"show", :controller=>"statuses", :id=>#<Status id: nil, uri: nil, text: "", created_at: nil, updated_at: nil, in_reply_to_id: nil, reblog_of_id: nil, url: nil, sensitive: true, visibility: "public", spoiler_text: "", reply: false, favourites_count: 0, reblogs_count: 0, language: nil, conversation_id: nil, local: nil, account_id: nil, application_id: nil, in_reply_to_account_id: nil, local_only: nil>}, possible unmatched constraints: [:account_username, :id]' duration=83.76 view=0.00 db=16.60
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] ActionView::Template::Error (No route matches {:account_username=>nil, :action=>"show", :controller=>"statuses", :id=>#<Status id: nil, uri: nil, text: "", created_at: nil, updated_at: nil, in_reply_to_id: nil, reblog_of_id: nil, url: nil, sensitive: true, visibility: "public", spoiler_text: "", reply: false, favourites_count: 0, reblogs_count: 0, language: nil, conversation_id: nil, local: nil, account_id: nil, application_id: nil, in_reply_to_account_id: nil, local_only: nil>}, possible unmatched constraints: [:account_username, :id]):
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]     4:       = image_tag action_log.account.avatar.url(:original), alt: '', width: 40, height: 40, class: 'avatar'
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]     5:     .log-entry__content
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]     6:       .log-entry__title
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]     7:         = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}", name: content_tag(:span, action_log.account.username, class: 'username'), target: content_tag(:span, log_target(action_log), class: 'target')).html_safe
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]     8:       .log-entry__timestamp
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]     9:         %time= l action_log.created_at
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]    10:     .spacer
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7]
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] app/lib/tag_manager.rb:44:in `url_for'
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] app/helpers/admin/action_logs_helper.rb:37:in `log_target_from_history'
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] app/helpers/admin/action_logs_helper.rb:8:in `log_target'
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] app/views/admin/action_logs/_action_log.html.haml:7:in `_app_views_admin_action_logs__action_log_html_haml___1692368033563013559_69844469519060'
Aug 16 14:41:02 Calion bundle[15858]: [525f5906-36ec-42de-997b-49f1d8640ca7] app/views/admin/action_logs/index.html.haml:4:in `_app_views_admin_action_logs_index_html_haml___292954870391082800_69844461456600'

```
I open an issue in glitch-soc because the log talk about template and glitch-soc change template... :)

Regard

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rhaamo** [comment]
I think it might be related to a deleted user, and log page crash.
There have been a fix pushed recently upstream IIRC.

**Comment by rhaamo** [comment]
whoops no, it's just an issue, upstream: https://github.com/tootsuite/mastodon/issues/8133

**Comment by Dryusdan** [comment]
In upstream ? Damn, I think all people have this problem no ? :thinking:

**Comment by ThibG** [comment]
Fixed upstream, and merged back into glitch-soc!

**Comment by Dryusdan** [comment]
The problem is not solved for me and I'm not alone. I report this on upstream
